# Generated by Django 4.0.4 on 2022-04-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myneibourhood', '0002_alter_neighbourhood_hood_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='hood_logo',
            field=models.ImageField(default='profile_photos/user', upload_to='', verbose_name='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_photos/user', upload_to='', verbose_name='profile_photos/'),
        ),
    ]
